Fiap.CorrecaoNac/Fiap.CorrecaoNac/Models/Avaliacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.CorrecaoNac.Models
{
    public class Avaliacao
    {
        public int AvaliacaoId { get; set; }
        public string Tema { get; set; }
        public DateTime Data { get; set; }
        public bool Sistema { get; set; }
        public Disciplina Disciplina { get; set; }
        public int DisciplinaId { get; set; }
    }
}

Fiap.CorrecaoNac/Fiap.CorrecaoNac/Models/Disciplina.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.CorrecaoNac.Models
{
    public class Disciplina
    {
        public int DisciplinaId { get; set; }
        public string Nome { get; set; }
        public string Ementa { get; set; }

        public List<Avaliacao> Avaliacoes { get; set; }
    }
}

Fiap.CorrecaoNac/Fiap.CorrecaoNac/Controllers/AvaliacaoController.cs
using Fiap.CorrecaoNac.Models;
using Fiap.CorrecaoNac.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.CorrecaoNac.Controllers
{
    public class AvaliacaoController : Controller
    {
        private NacContext _context = new NacContext();

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_context.Avaliacoes.Include("Disciplina").ToList());
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            var lista = _context.Disciplinas.ToList();
            ViewBag.lista = new SelectList(lista, "DisciplinaId", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Avaliacao avaliacao)
        {
            _context.Avaliacoes.Add(avaliacao);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado!";
            return RedirectToAction("Cadastrar");
        }
    }
}

Fiap.CorrecaoNac/Fiap.CorrecaoNac/Controllers/DisciplinaController.cs
using Fiap.CorrecaoNac.Models;
using Fiap.CorrecaoNac.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.CorrecaoNac.Controllers
{
    public class DisciplinaController : Controller
    {
        private NacContext _context = new NacContext();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Disciplina disciplina)
        {
            _context.Disciplinas.Add(disciplina);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado!";
            return RedirectToAction("Cadastrar");
        }
    }
}

Fiap.CorrecaoNac/Fiap.CorrecaoNac/Views/Disciplina/Cadastrar.cshtml
@model Fiap.CorrecaoNac.Models.Disciplina
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Disciplina</h2>
@if (TempData["msg"]!= null)
{
    <div class="alert alert-success">@TempData["msg"]</div>
}
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(d => d.Nome)
        @Html.TextBoxFor(d => d.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(dis => dis.Ementa)
        @Html.TextAreaFor(d => d.Ementa, new { @class = "form-control"})
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}

Fiap.CorrecaoNac/Fiap.CorrecaoNac/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Correção NAC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro de Disciplina","Cadastrar","Disciplina")</li>
                    <li>@Html.ActionLink("Cadastro de Avaliação", "Cadastrar", "Avaliacao")</li>
                    <li>@Html.ActionLink("Avaliações", "Listar", "Avaliacao")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>