Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo04.MVC.Models
{
    public class Animal
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "Espécie")]
        public string Especie { get; set; }

        public bool Carnivoro { get; set; }

        [Required]
        [Display(Name = "Data de Entrada")]
        public DateTime DataEntrada { get; set; }
    }
}

Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo04.MVC.Models
{
    public class Funcionario
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public bool Ativo { get; set; }

        public DateTime DataAdmissao { get; set; }
    }
}

Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Controllers/AnimalController.cs
using Fiap.Exemplo04.MVC.Models;
using Fiap.Exemplo04.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo04.MVC.Controllers
{
    public class AnimalController : Controller
    {
        private ZooContext _context = new ZooContext();

        public ActionResult Remover(int id)
        {
            var animal = _context.Animais.Find(id);
            _context.Animais.Remove(animal);
            _context.SaveChanges();
            TempData["msg"] = "Excluido";
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Alterar(Animal animal)
        {
            _context.Entry(animal).State = EntityState.Modified;
            _context.SaveChanges();
            TempData["msg"] = "Atualizado";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Alterar(int id)
        {
            return View(_context.Animais.Find(id));
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Animal animal)
        {
            _context.Animais.Add(animal);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado!";
            //Para não cadastrar varias vezes
            return RedirectToAction("Cadastrar");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_context.Animais.ToList());
        }
    }
}

Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Controllers/FuncionarioController.cs
using Fiap.Exemplo04.MVC.Models;
using Fiap.Exemplo04.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo04.MVC.Controllers
{
    public class FuncionarioController : Controller
    {
        private ZooContext _context = new ZooContext();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Funcionario funcionario)
        {
            _context.Funcionarios.Add(funcionario);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado!";
            return Redirect("Cadastrar");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_context.Funcionarios.ToList());
        }
    }
}

Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Views/Funcionario/Cadastrar.cshtml
@model Fiap.Exemplo04.MVC.Models.Funcionario
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Funcionário</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(f => f.Nome)
        @Html.TextBoxFor(f => f.Nome, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(f => f.DataAdmissao)
        @Html.TextBoxFor(f => f.DataAdmissao, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(f => f.Ativo)
        @Html.LabelFor(f => f.Ativo)
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}

Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Views/Funcionario/Listar.cshtml
@model List<Fiap.Exemplo04.MVC.Models.Funcionario>
@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Funcionários</h2>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Data de Admissão</th>
        <th>Ativo</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.DataAdmissao.ToShortDateString()</td>
            <td>@item.Ativo</td>
        </tr>
    }
</table>

Fiap.Exemplo04.MVC/Fiap.Exemplo04.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.theme.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP Zoo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Animal <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro","Cadastrar","Animal")</li>
                            <li>@Html.ActionLink("Lista","Listar","Animal")</li>                            
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Funcionario <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro", "Cadastrar", "Funcionario")</li>
                            <li>@Html.ActionLink("Lista", "Listar", "Funcionario")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>